language: csharp
mono: none
dotnet: 2.1.105
addons:
  sonarcloud:
    organization: "jialiuhunters-github" 
    token:
      secure: e84e206101d805815ae32947f5ad2e4df90864b4
script:   
  - dotnet restore
  - dotnet test ./cliTest/cliTest.csproj
  - sonar-scanner